name: TruffleHog Scan

on:
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run TruffleHog and save results
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/repo \
            ghcr.io/trufflesecurity/trufflehog:latest \
            filesystem /repo --json > trufflehog-results.json

      - name: Upload TruffleHog results
        uses: actions/upload-artifact@v4
        with:
          name: trufflehog-results
          path: trufflehog-results.json
